language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: h9WrVIWHfPQZNaPhiCM8IH8Qj1nOxD0OziwgJ9840YO0BLSH93Z04rmkn2y3bCX/yHp7CVRGLmoQgyzFDuHKZvcdldWA6RLYopDB7fKfeqwIyB1U6Fxo+987bD5vsz/N62RJRxfc68WMwXpHYfYVLnyrWJmT3SAN0tniFs1HbjjEiZ2DCOem4SCnQpgVwiVY2/ruqJPiIN5S3Yeih2+7xgGxKDCSXGvNBBC36mvYhaemBXiHoRX9me6VrCQp4IL3pPSALbWquDCuhXSY9fyv9oPjClfjw3+/vxdHgjDeGBMTSkZh0fgTxi1H+JKdpzYLP2m/tU5/jfhCbPEheOdml8UiNdvMOF6KOZgAowI+otjZfO74T2VLpIiSNujc9mB2meeTTk2MdZCFAeNSFSm8gjfrTWBIit1SJnSnpfCM/EkKgXsyGmYPrbtS7bjnlnNp9qAqGYKBn07PoF5e6Da0litLI/KAkdCll5+Hc//qZTMcuQbWbiKaeJTJYgUzw066oXrdeY+wRHcl8DtAlK5Ovhd/D7wZV+zEg2XvsBvXogKNIKdCg0lNd+KW3Ntmu5/ayvkY4g1MwF0nsRS6CyrUl8pxSqtxPDZfwuCzJQlSni0s2dCGXpI+h2GO7a27Upc1RCPGwVQb8pzqWXbUteAlayy/IAJWSlfWljiY2lwhVco=
  app: easyTravel
  skip_cleanup: true
